site_name: DataWiz Documentation
theme:
  name: material
  logo: assets/satrac-logo.png
  favicon: assets/datawiz-logo.png
  palette:
    primary: white
  features:
    - navigation.sections
    - toc.integrate # This puts the table of contents on the side for easy scrolling

nav:
  # - Home: index.md
  - Production Tracking: production_tracking.md
  - Subassembly Tracking: subassembly_tracking.md
  - Line Stoppage: line_stoppage.md
  - Quality Checksheets: quality_checksheets.md
  # - Contractor Billing: contractor_billing.md
  # - Planning & Scheduling: planning_and_scheduling.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption